from math import ceil

from tools import Rect

TILE_X = 32
TILE_Y = 32

WINDOW_X_SIZE = 40 * TILE_X
WINDOW_Y_SIZE = 20 * TILE_Y



MESSAGE_PANEL_X = 2
MESSAGE_PANEL_W = TILE_X - 4
MESSAGE_PANEL_H = 7
MESSAGE_PANEL_Y = TILE_Y - MESSAGE_PANEL_H - 1
MESSAGE_PANEL = Rect(MESSAGE_PANEL_X, MESSAGE_PANEL_Y, MESSAGE_PANEL_W, MESSAGE_PANEL_H)

MAP_PANEL_W = 20
MAP_PANEL_X = 1
MAP_PANEL_H = 20
MAP_PANEL_Y = 1
MAP_PANEL = Rect(MAP_PANEL_X, MAP_PANEL_Y, MAP_PANEL_W, MAP_PANEL_H)

STATS_PANEL_W = TILE_X - (MAP_PANEL_W + MAP_PANEL_X) - 2
STATS_PANEL_X = (MAP_PANEL_W + MAP_PANEL_X) + 2
STATS_PANEL_H = int((MAP_PANEL_H + MAP_PANEL_Y - 1) / 2) - 2
STATS_PANEL_Y = 1
STATS_PANEL = Rect(STATS_PANEL_X, STATS_PANEL_Y, STATS_PANEL_W, STATS_PANEL_H)

STATS_ENEMY_PANEL_W = STATS_PANEL_W
STATS_ENEMY_PANEL_X = STATS_PANEL_X
STATS_ENEMY_PANEL_H = int((MAP_PANEL_H + MAP_PANEL_Y - 1) / 2) - 2
STATS_ENEMY_PANEL_Y = STATS_PANEL_Y + STATS_PANEL_H + 1
STATS_ENEMY_PANEL = Rect(STATS_ENEMY_PANEL_X, STATS_ENEMY_PANEL_Y, STATS_ENEMY_PANEL_W, STATS_ENEMY_PANEL_H)

BUTTONS_PANEL_X = STATS_PANEL_X
BUTTONS_PANEL_Y = STATS_ENEMY_PANEL_Y + STATS_ENEMY_PANEL_H + 1
BUTTONS_PANEL_H = 2
BUTTONS_PANEL_W = STATS_PANEL_W
BUTTONS_PANEL = Rect(BUTTONS_PANEL_X, BUTTONS_PANEL_Y, BUTTONS_PANEL_W, BUTTONS_PANEL_H)

QUIT_KEY = (41, 224)
ACTION_KEY = (44,)
MOVEMENT_KEYS = {93: [0, 0], 90: [0, 1], 89: [-1, 1], 92: [-1, 0], 95: [-1, -1], 96: [0, -1], 97: [1, -1],
                 94: [1, 0], 91: [1, 1]}

TEAM_COLORS = ['blue', 'red', 'green', 'yellow']
ACTIVE_COLOR = 'green'

KEY = {'tab': 43}

ABBR = {'strength': 'str', 'agility': 'agi', 'intel': 'int', 'defence': 'def', 'hp': 'HP'}